syntax = "proto3";

package astrophysics;

service SimulationService {
  rpc StreamTelemetry (stream TelemetryFrame) returns (SimulationResponse);
}

// Data structure representing a single celestial body state
message BodyState {
  int32 id = 1;
  double mass = 2;
  double x = 3;
  double y = 4;
  double vx = 5;
  double vy = 6;
}

// A collection of all bodies in the universe at a specific moment in time
message TelemetryFrame {
  int64 frame_number = 1;
  double timestamp = 2;
  repeated BodyState bodies = 3;
}

// Acknowledgement
message SimulationResponse {
  bool success = 1;
  string sim_message = 2;
}