syntax = "proto3";

package astrophysics;

option go_package = "github.com/yernur/astrophysics_simulation/server/proto";

service SimulationService {
  rpc StreamTelemetry(stream TelemetryFrame) returns (SimulationResponse);
  rpc UploadScene(UploadSceneRequest) returns (UploadSceneResponse);
}

// Data structure representing a single celestial body state
message BodyState {
  int32 id = 1;
  double mass = 2;
  double x = 3;
  double y = 4;
  double vx = 5;
  double vy = 6;
  double radius = 7;
  bool alive = 8;
}

// A collection of all bodies in the universe at a specific moment in time
message TelemetryFrame {
  int64 frame_number = 1;
  double timestamp = 2;
  repeated BodyState bodies = 3;
}

// Acknowledgement
message SimulationResponse {
  bool success = 1;
  string sim_message = 2;
}

// control message for speed control
message SpeedRequest {
  double multiplier = 1;
}

message SpeedResponse {
  bool ok = 1;
  string message = 2;
}

// control service by the engine to accept speed updates
service SpeedService {
  rpc UpdateSpeed(SpeedRequest) returns (SpeedResponse);
}

// request by Go server for uploading a scene
message UploadSceneRequest {
  repeated BodyState bodies = 1;
}

// response from C++ engine confirming scene was loaded
message UploadSceneResponse {
  bool success = 1;
  string message = 2;
}

message ControlRequest {
  enum Command {
    PLAY = 0;
    PAUSE = 1;
  }
  Command command = 1;
}

message ControlResponse {
  bool success = 1;
  string message = 2;
}

service ControlService {
  rpc Control(ControlRequest) returns (ControlResponse);
}
