// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type Scene struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	Descriptions  pgtype.Text
	IsPublic      bool
	ShareToken    pgtype.Text
	EngineVersion pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type SceneBody struct {
	ID        pgtype.UUID
	SceneID   pgtype.UUID
	BodyIndex int32
	BodyID    int32
	Mass      float64
	Radius    float64
	X         float64
	Y         float64
	Vx        float64
	Vy        float64
	Alive     bool
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	DisplayName  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
