// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScene = `-- name: CreateScene :one
INSERT INTO scenes (id, user_id, name, is_public, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, user_id, name, is_public, created_at, updated_at
`

type CreateSceneParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Name     string
	IsPublic bool
}

type CreateSceneRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	IsPublic  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (CreateSceneRow, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.IsPublic,
	)
	var i CreateSceneRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScene = `-- name: DeleteScene :exec
DELETE FROM scenes WHERE id = $1
`

func (q *Queries) DeleteScene(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScene, id)
	return err
}

const getSceneBodiesBySceneId = `-- name: GetSceneBodiesBySceneId :many
SELECT body_id, mass, radius, x, y, vx, vy
FROM scene_bodies
WHERE scene_id = $1
`

type GetSceneBodiesBySceneIdRow struct {
	BodyID int32
	Mass   float64
	Radius float64
	X      float64
	Y      float64
	Vx     float64
	Vy     float64
}

func (q *Queries) GetSceneBodiesBySceneId(ctx context.Context, sceneID pgtype.UUID) ([]GetSceneBodiesBySceneIdRow, error) {
	rows, err := q.db.Query(ctx, getSceneBodiesBySceneId, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSceneBodiesBySceneIdRow
	for rows.Next() {
		var i GetSceneBodiesBySceneIdRow
		if err := rows.Scan(
			&i.BodyID,
			&i.Mass,
			&i.Radius,
			&i.X,
			&i.Y,
			&i.Vx,
			&i.Vy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenesByUserId = `-- name: GetScenesByUserId :many
SELECT id, name, created_at, updated_at
FROM scenes
WHERE user_id = $1
ORDER BY updated_at DESC
`

type GetScenesByUserIdRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetScenesByUserId(ctx context.Context, userID pgtype.UUID) ([]GetScenesByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getScenesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScenesByUserIdRow
	for rows.Next() {
		var i GetScenesByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSceneBody = `-- name: InsertSceneBody :exec
INSERT INTO scene_bodies (id, scene_id, body_index, body_id, mass, radius, x, y, vx, vy, alive)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertSceneBodyParams struct {
	ID        pgtype.UUID
	SceneID   pgtype.UUID
	BodyIndex int32
	BodyID    int32
	Mass      float64
	Radius    float64
	X         float64
	Y         float64
	Vx        float64
	Vy        float64
	Alive     bool
}

func (q *Queries) InsertSceneBody(ctx context.Context, arg InsertSceneBodyParams) error {
	_, err := q.db.Exec(ctx, insertSceneBody,
		arg.ID,
		arg.SceneID,
		arg.BodyIndex,
		arg.BodyID,
		arg.Mass,
		arg.Radius,
		arg.X,
		arg.Y,
		arg.Vx,
		arg.Vy,
		arg.Alive,
	)
	return err
}
