// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlRequest_Command int32

const (
	ControlRequest_PLAY  ControlRequest_Command = 0
	ControlRequest_PAUSE ControlRequest_Command = 1
)

// Enum value maps for ControlRequest_Command.
var (
	ControlRequest_Command_name = map[int32]string{
		0: "PLAY",
		1: "PAUSE",
	}
	ControlRequest_Command_value = map[string]int32{
		"PLAY":  0,
		"PAUSE": 1,
	}
)

func (x ControlRequest_Command) Enum() *ControlRequest_Command {
	p := new(ControlRequest_Command)
	*p = x
	return p
}

func (x ControlRequest_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlRequest_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_simulation_proto_enumTypes[0].Descriptor()
}

func (ControlRequest_Command) Type() protoreflect.EnumType {
	return &file_simulation_proto_enumTypes[0]
}

func (x ControlRequest_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlRequest_Command.Descriptor instead.
func (ControlRequest_Command) EnumDescriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{7, 0}
}

// Data structure representing a single celestial body state
type BodyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mass          float64                `protobuf:"fixed64,2,opt,name=mass,proto3" json:"mass,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Vx            float64                `protobuf:"fixed64,5,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            float64                `protobuf:"fixed64,6,opt,name=vy,proto3" json:"vy,omitempty"`
	Radius        float64                `protobuf:"fixed64,7,opt,name=radius,proto3" json:"radius,omitempty"`
	Alive         bool                   `protobuf:"varint,8,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyState) Reset() {
	*x = BodyState{}
	mi := &file_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyState) ProtoMessage() {}

func (x *BodyState) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyState.ProtoReflect.Descriptor instead.
func (*BodyState) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *BodyState) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BodyState) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *BodyState) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BodyState) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BodyState) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *BodyState) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *BodyState) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *BodyState) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

// A collection of all bodies in the universe at a specific moment in time
type TelemetryFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   int64                  `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Bodies        []*BodyState           `protobuf:"bytes,3,rep,name=bodies,proto3" json:"bodies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryFrame) Reset() {
	*x = TelemetryFrame{}
	mi := &file_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFrame) ProtoMessage() {}

func (x *TelemetryFrame) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFrame.ProtoReflect.Descriptor instead.
func (*TelemetryFrame) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryFrame) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *TelemetryFrame) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryFrame) GetBodies() []*BodyState {
	if x != nil {
		return x.Bodies
	}
	return nil
}

// Acknowledgement
type SimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SimMessage    string                 `protobuf:"bytes,2,opt,name=sim_message,json=simMessage,proto3" json:"sim_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationResponse) Reset() {
	*x = SimulationResponse{}
	mi := &file_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResponse) ProtoMessage() {}

func (x *SimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResponse.ProtoReflect.Descriptor instead.
func (*SimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulationResponse) GetSimMessage() string {
	if x != nil {
		return x.SimMessage
	}
	return ""
}

// control message for speed control
type SpeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiplier    float64                `protobuf:"fixed64,1,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedRequest) Reset() {
	*x = SpeedRequest{}
	mi := &file_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedRequest) ProtoMessage() {}

func (x *SpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedRequest.ProtoReflect.Descriptor instead.
func (*SpeedRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *SpeedRequest) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type SpeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedResponse) Reset() {
	*x = SpeedResponse{}
	mi := &file_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedResponse) ProtoMessage() {}

func (x *SpeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedResponse.ProtoReflect.Descriptor instead.
func (*SpeedResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *SpeedResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SpeedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// request by Go server for uploading a scene
type UploadSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bodies        []*BodyState           `protobuf:"bytes,1,rep,name=bodies,proto3" json:"bodies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSceneRequest) Reset() {
	*x = UploadSceneRequest{}
	mi := &file_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSceneRequest) ProtoMessage() {}

func (x *UploadSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSceneRequest.ProtoReflect.Descriptor instead.
func (*UploadSceneRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *UploadSceneRequest) GetBodies() []*BodyState {
	if x != nil {
		return x.Bodies
	}
	return nil
}

// response from C++ engine confirming scene was loaded
type UploadSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSceneResponse) Reset() {
	*x = UploadSceneResponse{}
	mi := &file_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSceneResponse) ProtoMessage() {}

func (x *UploadSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSceneResponse.ProtoReflect.Descriptor instead.
func (*UploadSceneResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *UploadSceneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadSceneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       ControlRequest_Command `protobuf:"varint,1,opt,name=command,proto3,enum=astrophysics.ControlRequest_Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *ControlRequest) GetCommand() ControlRequest_Command {
	if x != nil {
		return x.Command
	}
	return ControlRequest_PLAY
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_simulation_proto protoreflect.FileDescriptor

const file_simulation_proto_rawDesc = "" +
	"\n" +
	"\x10simulation.proto\x12\fastrophysics\"\x99\x01\n" +
	"\tBodyState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mass\x18\x02 \x01(\x01R\x04mass\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x0e\n" +
	"\x02vx\x18\x05 \x01(\x01R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x06 \x01(\x01R\x02vy\x12\x16\n" +
	"\x06radius\x18\a \x01(\x01R\x06radius\x12\x14\n" +
	"\x05alive\x18\b \x01(\bR\x05alive\"\x82\x01\n" +
	"\x0eTelemetryFrame\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x03R\vframeNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x12/\n" +
	"\x06bodies\x18\x03 \x03(\v2\x17.astrophysics.BodyStateR\x06bodies\"O\n" +
	"\x12SimulationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vsim_message\x18\x02 \x01(\tR\n" +
	"simMessage\".\n" +
	"\fSpeedRequest\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x01 \x01(\x01R\n" +
	"multiplier\"9\n" +
	"\rSpeedResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x12UploadSceneRequest\x12/\n" +
	"\x06bodies\x18\x01 \x03(\v2\x17.astrophysics.BodyStateR\x06bodies\"I\n" +
	"\x13UploadSceneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x0eControlRequest\x12>\n" +
	"\acommand\x18\x01 \x01(\x0e2$.astrophysics.ControlRequest.CommandR\acommand\"\x1e\n" +
	"\aCommand\x12\b\n" +
	"\x04PLAY\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\"E\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbc\x01\n" +
	"\x11SimulationService\x12S\n" +
	"\x0fStreamTelemetry\x12\x1c.astrophysics.TelemetryFrame\x1a .astrophysics.SimulationResponse(\x01\x12R\n" +
	"\vUploadScene\x12 .astrophysics.UploadSceneRequest\x1a!.astrophysics.UploadSceneResponse2V\n" +
	"\fSpeedService\x12F\n" +
	"\vUpdateSpeed\x12\x1a.astrophysics.SpeedRequest\x1a\x1b.astrophysics.SpeedResponse2X\n" +
	"\x0eControlService\x12F\n" +
	"\aControl\x12\x1c.astrophysics.ControlRequest\x1a\x1d.astrophysics.ControlResponseB8Z6github.com/yernur/astrophysics_simulation/server/protob\x06proto3"

var (
	file_simulation_proto_rawDescOnce sync.Once
	file_simulation_proto_rawDescData []byte
)

func file_simulation_proto_rawDescGZIP() []byte {
	file_simulation_proto_rawDescOnce.Do(func() {
		file_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)))
	})
	return file_simulation_proto_rawDescData
}

var file_simulation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_simulation_proto_goTypes = []any{
	(ControlRequest_Command)(0), // 0: astrophysics.ControlRequest.Command
	(*BodyState)(nil),           // 1: astrophysics.BodyState
	(*TelemetryFrame)(nil),      // 2: astrophysics.TelemetryFrame
	(*SimulationResponse)(nil),  // 3: astrophysics.SimulationResponse
	(*SpeedRequest)(nil),        // 4: astrophysics.SpeedRequest
	(*SpeedResponse)(nil),       // 5: astrophysics.SpeedResponse
	(*UploadSceneRequest)(nil),  // 6: astrophysics.UploadSceneRequest
	(*UploadSceneResponse)(nil), // 7: astrophysics.UploadSceneResponse
	(*ControlRequest)(nil),      // 8: astrophysics.ControlRequest
	(*ControlResponse)(nil),     // 9: astrophysics.ControlResponse
}
var file_simulation_proto_depIdxs = []int32{
	1, // 0: astrophysics.TelemetryFrame.bodies:type_name -> astrophysics.BodyState
	1, // 1: astrophysics.UploadSceneRequest.bodies:type_name -> astrophysics.BodyState
	0, // 2: astrophysics.ControlRequest.command:type_name -> astrophysics.ControlRequest.Command
	2, // 3: astrophysics.SimulationService.StreamTelemetry:input_type -> astrophysics.TelemetryFrame
	6, // 4: astrophysics.SimulationService.UploadScene:input_type -> astrophysics.UploadSceneRequest
	4, // 5: astrophysics.SpeedService.UpdateSpeed:input_type -> astrophysics.SpeedRequest
	8, // 6: astrophysics.ControlService.Control:input_type -> astrophysics.ControlRequest
	3, // 7: astrophysics.SimulationService.StreamTelemetry:output_type -> astrophysics.SimulationResponse
	7, // 8: astrophysics.SimulationService.UploadScene:output_type -> astrophysics.UploadSceneResponse
	5, // 9: astrophysics.SpeedService.UpdateSpeed:output_type -> astrophysics.SpeedResponse
	9, // 10: astrophysics.ControlService.Control:output_type -> astrophysics.ControlResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_simulation_proto_init() }
func file_simulation_proto_init() {
	if File_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_simulation_proto_goTypes,
		DependencyIndexes: file_simulation_proto_depIdxs,
		EnumInfos:         file_simulation_proto_enumTypes,
		MessageInfos:      file_simulation_proto_msgTypes,
	}.Build()
	File_simulation_proto = out.File
	file_simulation_proto_goTypes = nil
	file_simulation_proto_depIdxs = nil
}
