// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data structure representing a single celestial body state
type BodyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mass          float64                `protobuf:"fixed64,2,opt,name=mass,proto3" json:"mass,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Vx            float64                `protobuf:"fixed64,5,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            float64                `protobuf:"fixed64,6,opt,name=vy,proto3" json:"vy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyState) Reset() {
	*x = BodyState{}
	mi := &file_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyState) ProtoMessage() {}

func (x *BodyState) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyState.ProtoReflect.Descriptor instead.
func (*BodyState) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *BodyState) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BodyState) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *BodyState) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BodyState) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BodyState) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *BodyState) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

// A collection of all bodies in the universe at a specific moment in time
type TelemetryFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   int64                  `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Bodies        []*BodyState           `protobuf:"bytes,3,rep,name=bodies,proto3" json:"bodies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryFrame) Reset() {
	*x = TelemetryFrame{}
	mi := &file_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFrame) ProtoMessage() {}

func (x *TelemetryFrame) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFrame.ProtoReflect.Descriptor instead.
func (*TelemetryFrame) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryFrame) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *TelemetryFrame) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryFrame) GetBodies() []*BodyState {
	if x != nil {
		return x.Bodies
	}
	return nil
}

// Acknowledgement
type SimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SimMessage    string                 `protobuf:"bytes,2,opt,name=sim_message,json=simMessage,proto3" json:"sim_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationResponse) Reset() {
	*x = SimulationResponse{}
	mi := &file_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResponse) ProtoMessage() {}

func (x *SimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResponse.ProtoReflect.Descriptor instead.
func (*SimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulationResponse) GetSimMessage() string {
	if x != nil {
		return x.SimMessage
	}
	return ""
}

var File_simulation_proto protoreflect.FileDescriptor

const file_simulation_proto_rawDesc = "" +
	"\n" +
	"\x10simulation.proto\x12\fastrophysics\"k\n" +
	"\tBodyState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mass\x18\x02 \x01(\x01R\x04mass\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x0e\n" +
	"\x02vx\x18\x05 \x01(\x01R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x06 \x01(\x01R\x02vy\"\x82\x01\n" +
	"\x0eTelemetryFrame\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x03R\vframeNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x12/\n" +
	"\x06bodies\x18\x03 \x03(\v2\x17.astrophysics.BodyStateR\x06bodies\"O\n" +
	"\x12SimulationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vsim_message\x18\x02 \x01(\tR\n" +
	"simMessage2h\n" +
	"\x11SimulationService\x12S\n" +
	"\x0fStreamTelemetry\x12\x1c.astrophysics.TelemetryFrame\x1a .astrophysics.SimulationResponse(\x01B8Z6github.com/yernur/astrophysics_simulation/server/protob\x06proto3"

var (
	file_simulation_proto_rawDescOnce sync.Once
	file_simulation_proto_rawDescData []byte
)

func file_simulation_proto_rawDescGZIP() []byte {
	file_simulation_proto_rawDescOnce.Do(func() {
		file_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)))
	})
	return file_simulation_proto_rawDescData
}

var file_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simulation_proto_goTypes = []any{
	(*BodyState)(nil),          // 0: astrophysics.BodyState
	(*TelemetryFrame)(nil),     // 1: astrophysics.TelemetryFrame
	(*SimulationResponse)(nil), // 2: astrophysics.SimulationResponse
}
var file_simulation_proto_depIdxs = []int32{
	0, // 0: astrophysics.TelemetryFrame.bodies:type_name -> astrophysics.BodyState
	1, // 1: astrophysics.SimulationService.StreamTelemetry:input_type -> astrophysics.TelemetryFrame
	2, // 2: astrophysics.SimulationService.StreamTelemetry:output_type -> astrophysics.SimulationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simulation_proto_init() }
func file_simulation_proto_init() {
	if File_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulation_proto_goTypes,
		DependencyIndexes: file_simulation_proto_depIdxs,
		MessageInfos:      file_simulation_proto_msgTypes,
	}.Build()
	File_simulation_proto = out.File
	file_simulation_proto_goTypes = nil
	file_simulation_proto_depIdxs = nil
}
